# Generated by Django 4.2.2 on 2023-06-23 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('INGRESO', 'INGRESO'), ('EGRESO', 'EGRESO')], default='EGRESO', max_length=7)),
                ('realizado', models.BooleanField(default=False)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('day_move', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.day')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('egresos_hoy', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ingresos_hoy', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('saldo_hoy', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.day')),
            ],
        ),
    ]
