# Generated by Django 4.2.2 on 2023-06-22 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_move_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Move',
        ),
    ]
