# Generated by Django 4.2.2 on 2023-06-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_accountbalance_move_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='move',
            field=models.ManyToManyField(related_name='move', to='core.move'),
        ),
    ]
