# Generated by Django 4.2.2 on 2023-06-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_history_move'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='day',
        ),
        migrations.AddField(
            model_name='day',
            name='history',
            field=models.ManyToManyField(blank=True, to='core.history'),
        ),
        migrations.AddField(
            model_name='history',
            name='gastos_hoy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='saldo_ayer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='saldo_hoy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='move',
            field=models.ManyToManyField(blank=True, to='core.move'),
        ),
    ]
