# Generated by Django 4.2.2 on 2023-06-22 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_history_day_day_history_history_gastos_hoy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='history',
        ),
        migrations.AddField(
            model_name='move',
            name='day_move',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.day'),
        ),
    ]
