# Generated by Django 4.2.2 on 2023-06-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_day_history_move_day_move'),
    ]

    operations = [
        migrations.RenameField(
            model_name='move',
            old_name='egreso',
            new_name='realizado',
        ),
        migrations.RemoveField(
            model_name='move',
            name='ingreso',
        ),
        migrations.AddField(
            model_name='move',
            name='tipo',
            field=models.CharField(choices=[('INGRESO', 'INGRESO'), ('EGRESO', 'EGRESO')], default='EGRESO', max_length=7),
        ),
    ]
