# Generated by Django 4.2.2 on 2023-06-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_egreso_move_realizado_remove_move_ingreso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
